### ISSUE TITLE
Messages from discord not parsed correctly

### ISSUE THREAD

**Issue by xorinzor** [ErdbeerbaerLP/Discord-Integration-Fabric#19] opened 2022-12-25 22:00 UTC
Something seems to be going wrong when the mod converts the discord message -> MC chat message.

server log shows the message correctly:
![image](https://user-images.githubusercontent.com/4212335/209482955-2551111a-e9b8-4ce4-8310-3c11737bec82.png)

but in-game it gets rendered as:
![image](https://user-images.githubusercontent.com/4212335/209482962-fa563191-0ad2-4827-b429-5860c9edec03.png)

Using this in the config:
```
ingame_discordMessage = "§6[§5DISCORD§6]§r<%user%> %msg%"
```

Was using the latest "release" (2.4.7), but also tried the latest "beta" (2.5.0) to the same result.

**Comment by Avakining** [comment] 2023-01-14 20:24
This happens when a mod (like FTB Teams) messes with chat -- see #5

**Comment by ErdbeerbaerLP** [comment] 2023-03-23 08:47
closed as duplicate of #5

**Closed by ErdbeerbaerLP** 2023-03-23 08:47 UTC
